# Generated by Django 5.0.1 on 2026-09-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0002_remove_userprofile_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Water', 'Water'), ('Power', 'Power'), ('Housekeeping', 'Housekeeping'), ('Gym', 'Gym'), ('Pool', 'Pool')], default='Water', max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='flat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_flat_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
