# Generated by Django 5.0.1 on 2026-09-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0003_issue_category_issue_flat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
