# Generated by Django 5.0.1 on 2026-09-02 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0004_alter_issue_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_from', models.CharField(blank=True, max_length=50, null=True)),
                ('status_to', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('proof_metadata_url', models.URLField(blank=True, max_length=500, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='apt_proj.issue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"apt_data"."apt_proj_issuetimeline"',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='IssueComment',
        ),
    ]
