# Generated by Django 5.0.14 on 2026-09-18 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0010_alter_issue_status_alter_notice_category_devicetoken_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='media',
            name='obj_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='upload_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
    ]
