# Generated by Django 5.0.14 on 2026-09-18 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0011_media_content_type_media_obj_id_media_upload_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeattachment',
            name='notice',
        ),
        migrations.RenameField(
            model_name='noticeapproval',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='noticeapproval',
            name='decision_at',
        ),
        migrations.AddField(
            model_name='noticeacknowledgement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticeacknowledgement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noticeapproval',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='IssueAttachment',
        ),
        migrations.DeleteModel(
            name='NoticeAttachment',
        ),
    ]
