# Generated by Django 5.0.14 on 2026-09-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0012_remove_noticeattachment_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='signed_url',
            field=models.URLField(blank=True, help_text='Cached 7-day signed URL', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='signed_url_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
