# Generated by Django 5.0.14 on 2026-09-21 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0013_media_signed_url_media_signed_url_expires'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CHECKED_OUT', 'Checked Out')], default='PENDING_APPROVAL', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_logs', to='apt_proj.flat')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"apt_data"."apt_proj_visitor_log"',
                'ordering': ['-created_at'],
            },
        ),
    ]
