# Generated by Django 5.0.14 on 2026-10-01 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0015_amenity_amenitybooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('GATE_SECURITY', 'Gate Security'), ('FACILITY_MGMT', 'Facility Management'), ('AMBULANCE_MEDICAL', 'Ambulance & Medical'), ('POLICE', 'Police Station'), ('FIRE_STATION', 'Fire Station'), ('DISASTER_MGMT', 'Disaster Management'), ('UTILITY_EMERGENCY', 'Electricity & Water'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': '"apt_data"."apt_proj_emergencycontact"',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical (Life / Property Threat)'), ('HIGH', 'High (Urgent Attention Required)'), ('WARNING', 'Warning (Precautionary)'), ('INFO', 'Informational')], default='CRITICAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('broadcast_metadata', models.JSONField(blank=True, default=dict)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"apt_data"."apt_proj_emergencybroadcast"',
                'ordering': ['-created_at'],
            },
        ),
    ]
