# Generated by Django 5.0.14 on 2026-10-01 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0016_emergencycontact_emergencybroadcast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'notifications_enabled'], name='device_user_notif_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['updated_at'], name='device_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='issue_status_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['created_at'], name='issue_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', 'created_at'], name='issue_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['status'], name='notice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['publish_date'], name='notice_publish_date_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['status', 'publish_date'], name='notice_status_publish_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['flat', 'created_at'], name='visitor_flat_date_idx'),
        ),
    ]
