# Generated by Django 5.2.17 on 2026-10-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0017_devicetoken_device_user_notif_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeacknowledgement',
            name='acknowledgement_time',
        ),
        migrations.AlterField(
            model_name='noticeacknowledgement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Acknowledged', 'Acknowledged'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
