# Generated by Django 5.2.17 on 2026-10-06 12:09

from django.db import migrations

RENAME_TABLES = [
    ('amenity', 'apt_proj_amenity', 'amenities'),
    ('amenitybooking', 'apt_proj_amenitybooking', 'amenity_bookings'),
    ('block', 'apt_proj_block', 'blocks'),
    ('devicetoken', 'apt_proj_devicetoken', 'device_tokens'),
    ('emergencybroadcast', 'apt_proj_emergencybroadcast', 'emergency_broadcasts'),
    ('emergencycontact', 'apt_proj_emergencycontact', 'emergency_contacts'),
    ('flat', 'apt_proj_flat', 'flats'),
    ('issue', 'apt_proj_issue', 'issues'),
    ('issuecategory', 'apt_proj_issuecategory', 'issue_categories'),
    ('issuetimeline', 'apt_proj_issuetimeline', 'issue_timelines'),
    ('media', 'apt_proj_media', 'media'),
    ('notice', 'apt_proj_notice', 'notices'),
    ('noticeacknowledgement', 'apt_proj_noticeacknowledgement', 'notice_acknowledgements'),
    ('noticeapproval', 'apt_proj_noticeapproval', 'notice_approvals'),
    ('role', 'apt_proj_role', 'roles'),
    ('userprofile', 'apt_proj_userprofile', 'user_profiles'),
    ('visitorlog', 'apt_proj_visitor_log', 'visitor_logs'),
]

class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0018_remove_noticeacknowledgement_acknowledgement_time_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name=model_name,
                    table=f'"apt_data"."{new_name}"',
                )
                for model_name, old_name, new_name in RENAME_TABLES
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=f'ALTER TABLE IF EXISTS "apt_data"."{old_name}" RENAME TO "{new_name}";',
                    reverse_sql=f'ALTER TABLE IF EXISTS "apt_data"."{new_name}" RENAME TO "{old_name}";',
                )
                for model_name, old_name, new_name in RENAME_TABLES
            ]
        )
    ]
