# Generated by Django 5.2.17 on 2026-10-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0019_alter_amenity_table_alter_amenitybooking_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitybooking',
            name='timeline',
            field=models.JSONField(default=list),
        ),
    ]
