# Generated by Django 5.2.17 on 2026-10-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0020_amenitybooking_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_residents', to='apt_proj.userprofile')),
            ],
            options={
                'db_table': '"apt_data"."co_residents"',
            },
        ),
        migrations.CreateModel(
            name='PersonalEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_emergency_contacts', to='apt_proj.userprofile')),
            ],
            options={
                'db_table': '"apt_data"."personal_emergency_contacts"',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Other', 'Other')], default='Car', max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='apt_proj.userprofile')),
            ],
            options={
                'db_table': '"apt_data"."vehicles"',
            },
        ),
    ]
