# Generated by Django 5.0.1 on 2026-09-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role_name',
        ),
    ]
