# Generated by Django 5.0.1 on 2026-09-03 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0005_issuetimeline_delete_issuecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"apt_data"."apt_proj_issuecategory"',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='issue',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_flat_specific',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolution_notes',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='apt_proj.issuecategory'),
        ),
    ]
