# Generated by Django 5.0.1 on 2026-09-03 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0006_issuecategory_remove_issue_flat_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='issues/attachments/')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='apt_proj.issue')),
            ],
            options={
                'db_table': '"apt_data"."apt_proj_issueattachment"',
                'ordering': ['created_at'],
            },
        ),
    ]
