# Generated by Django 5.0.1 on 2026-09-03 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_proj', '0007_issueattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuetimeline',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='issuetimeline',
            name='proof_metadata_url',
        ),
        migrations.RemoveField(
            model_name='issuetimeline',
            name='status_from',
        ),
        migrations.RemoveField(
            model_name='issuetimeline',
            name='status_to',
        ),
        migrations.RemoveField(
            model_name='issuetimeline',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='issuetimeline',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='issuetimeline',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_record', to='apt_proj.issue'),
        ),
    ]
